from neo4j import GraphDatabase
import time

uri = "bolt://localhost:7687"
user_name = "codyowl"
password = "optimus1234" 
db_name = "cypheropti"

# raw data
nodes = [
    # GENRE Nodes
    {"node_label": "GENRE", "genre_name": "Action"},
    {"node_label": "GENRE", "genre_name": "Comedy"},
    {"node_label": "GENRE", "genre_name": "Drama"},
    {"node_label": "GENRE", "genre_name": "Sci-Fi"},
    {"node_label": "GENRE", "genre_name": "Fantasy"},
    {"node_label": "GENRE", "genre_name": "Romance"},
    {"node_label": "GENRE", "genre_name": "Thriller"},
    {"node_label": "GENRE", "genre_name": "Adventure"},
    {"node_label": "GENRE", "genre_name": "Horror"},
    {"node_label": "GENRE", "genre_name": "Mystery"},
    {"node_label": "GENRE", "genre_name": "Animation"},
    {"node_label": "GENRE", "genre_name": "Biography"},
    {"node_label": "GENRE", "genre_name": "Music"},
    {"node_label": "GENRE", "genre_name": "Crime"},
    {"node_label": "GENRE", "genre_name": "Family"},

    # MOVIE Nodes
    {"node_label": "MOVIE", "movie_name": "Mad Max", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "The Hangover", "genre_name": "Comedy"},
    {"node_label": "MOVIE", "movie_name": "The Pursuit of Happyness", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "John Wick", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Superbad", "genre_name": "Comedy"},
    {"node_label": "MOVIE", "movie_name": "Interstellar", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Lord of the Rings: The Return of the King", "genre_name": "Fantasy"},
    {"node_label": "MOVIE", "movie_name": "Titanic", "genre_name": "Romance"},
    {"node_label": "MOVIE", "movie_name": "The Dark Knight", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Inception", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Matrix", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "Guardians of the Galaxy", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Avengers: Endgame", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "The Godfather", "genre_name": "Crime"},
    {"node_label": "MOVIE", "movie_name": "The Lion King", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "Gladiator", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "The Shining", "genre_name": "Horror"},
    {"node_label": "MOVIE", "movie_name": "Schindler's List", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "The Usual Suspects", "genre_name": "Mystery"},
    {"node_label": "MOVIE", "movie_name": "The Social Network", "genre_name": "Biography"},
    {"node_label": "MOVIE", "movie_name": "Pulp Fiction", "genre_name": "Crime"},
    {"node_label": "MOVIE", "movie_name": "The Godfather: Part II", "genre_name": "Crime"},
    {"node_label": "MOVIE", "movie_name": "Forrest Gump", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "Fight Club", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "Star Wars: The Empire Strikes Back", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Wizard of Oz", "genre_name": "Fantasy"},
    {"node_label": "MOVIE", "movie_name": "The Breakfast Club", "genre_name": "Comedy"},
    {"node_label": "MOVIE", "movie_name": "Back to the Future", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Revenant", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "The Prestige", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "Avengers: Infinity War", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Shutter Island", "genre_name": "Thriller"},
    {"node_label": "MOVIE", "movie_name": "Avatar", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "Inglourious Basterds", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "The Dark Knight Rises", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Jaws", "genre_name": "Horror"},
    {"node_label": "MOVIE", "movie_name": "Casablanca", "genre_name": "Romance"},
    {"node_label": "MOVIE", "movie_name": "Star Wars: A New Hope", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Matrix Reloaded", "genre_name": "Sci-Fi"},
    {"node_label": "MOVIE", "movie_name": "The Princess Bride", "genre_name": "Fantasy"},
    {"node_label": "MOVIE", "movie_name": "Jurassic Park", "genre_name": "Adventure"},
    {"node_label": "MOVIE", "movie_name": "The Truman Show", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "The Incredibles", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "The Lion King", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "Terminator 2: Judgment Day", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "The Big Lebowski", "genre_name": "Comedy"},
    {"node_label": "MOVIE", "movie_name": "The Green Mile", "genre_name": "Drama"},
    {"node_label": "MOVIE", "movie_name": "The Iron Giant", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "Frozen", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "The Avengers", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "Spider-Man: Into the Spider-Verse", "genre_name": "Animation"},
    {"node_label": "MOVIE", "movie_name": "Mad Max: Fury Road", "genre_name": "Action"},
    {"node_label": "MOVIE", "movie_name": "E.T. the Extra-Terrestrial", "genre_name": "Sci-Fi"},
    
    # KEYWORD Nodes - additional keywords to reach 20 for each movie
    {"node_label": "KEYWORD", "keyword_name": "post-apocalyptic", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "revenge", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "action-packed", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "explosions", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "survival", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "car chase", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "wasteland", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "fury", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "road warrior", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "dystopia", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "rebellion", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "feminism", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "combat", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "gasoline", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "action hero", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "brutality", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "fighting for survival", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "futuristic", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "escape", "movie_name": "Mad Max"},
    {"node_label": "KEYWORD", "keyword_name": "mutants", "movie_name": "Mad Max"},

    # The Hangover
    {"node_label": "KEYWORD", "keyword_name": "las vegas", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "comedy", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "friendship", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "bachelor party", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "blackout", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "misunderstandings", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "unexpected situations", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "wild night", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "hilarious", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "crazy events", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "adventure", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "romantic entanglements", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "criminal activity", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "identity crisis", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "alcohol", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "regret", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "group bonding", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "chaos", "movie_name": "The Hangover"},
    {"node_label": "KEYWORD", "keyword_name": "mystery", "movie_name": "The Hangover"},

    # The Pursuit of Happyness
    {"node_label": "KEYWORD", "keyword_name": "inspiration", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "motivation", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "poverty", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "fatherhood", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "hard work", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "dreams", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "struggle", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "hope", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "success", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "poverty to riches", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "single father", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "determination", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "job search", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "overcoming adversity", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "emotional", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "self-belief", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "sacrifice", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "parenting", "movie_name": "The Pursuit of Happyness"},
    {"node_label": "KEYWORD", "keyword_name": "work-life balance", "movie_name": "The Pursuit of Happyness"},

    # John Wick
    {"node_label": "KEYWORD", "keyword_name": "revenge", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "action-packed", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "assassin", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "guns", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "fighting", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "martial arts", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "crime syndicate", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "underworld", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "iconic", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "dog", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "vigilante", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "action hero", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "brutality", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "revenge-driven", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "gun fu", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "hitman", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "fast-paced", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "underdog", "movie_name": "John Wick"},
    {"node_label": "KEYWORD", "keyword_name": "loyalty", "movie_name": "John Wick"},

    # Superbad
    {"node_label": "KEYWORD", "keyword_name": "high school", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "coming of age", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "awkward", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "friendship", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "teen comedy", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "parties", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "crushes", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "underage drinking", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "humor", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "awkward moments", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "mischief", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "friends' journey", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "emotional growth", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "coming of age story", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "romance", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "teenage years", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "high school life", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "funny", "movie_name": "Superbad"},
    {"node_label": "KEYWORD", "keyword_name": "awkward situations", "movie_name": "Superbad"},

    # Interstellar
    {"node_label": "KEYWORD", "keyword_name": "space", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "time travel", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "science fiction", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "astronauts", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "black hole", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "planets", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "love", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "human survival", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "gravity", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "futuristic", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "emotion", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "space exploration", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "dimensions", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "humanity", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "interstellar travel", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "father-daughter", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "universe", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "science", "movie_name": "Interstellar"},
    {"node_label": "KEYWORD", "keyword_name": "emotionally intense", "movie_name": "Interstellar"},

    # The Lord of the Rings: The Return of the King
    {"node_label": "KEYWORD", "keyword_name": "epic fantasy", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "battle", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "journey", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Frodo Baggins", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Samwise Gamgee", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Gandalf", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "orc army", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "kingdoms", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Sauron", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Gondor", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "Ring of Power", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "elves", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "hobbits", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "friendship", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "loyalty", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "war", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "final battle", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "sacrifice", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "fellowship", "movie_name": "The Lord of the Rings: The Return of the King"},
    {"node_label": "KEYWORD", "keyword_name": "heroic journey", "movie_name": "The Lord of the Rings: The Return of the King"},

    # Titanic
    {"node_label": "KEYWORD", "keyword_name": "romance", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "shipwreck", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "love story", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "tragic ending", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "Jack Dawson", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "Rose DeWitt Bukater", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "iceberg", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "wealth vs poverty", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "class differences", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "disaster", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "1912", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "unsinkable", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "heart of the ocean", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "ship of dreams", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "survival", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "history", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "tragic romance", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "loss", "movie_name": "Titanic"},
    {"node_label": "KEYWORD", "keyword_name": "eternal love", "movie_name": "Titanic"},

    # The Dark Knight
    {"node_label": "KEYWORD", "keyword_name": "Batman", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "Joker", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "chaos", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "vigilante", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "Gotham City", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "morality", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "crime", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "corruption", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "superhero", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "action", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "psychology", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "dark knight", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "anarchy", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "duality", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "hero vs villain", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "insanity", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "tragedy", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "Batman vs Joker", "movie_name": "The Dark Knight"},
    {"node_label": "KEYWORD", "keyword_name": "superhero noir", "movie_name": "The Dark Knight"},

    # Inception
    {"node_label": "KEYWORD", "keyword_name": "dreams", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "mind-bending", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "reality", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "subconscious", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "Leonardo DiCaprio", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "heist", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "mind manipulation", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "layers of dreams", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "time", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "memories", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "paradox", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "cobb", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "mind heist", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "reality vs illusion", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "dream within a dream", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "emotion", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "philosophy", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "action thriller", "movie_name": "Inception"},
    {"node_label": "KEYWORD", "keyword_name": "ambiguous ending", "movie_name": "Inception"},

    # The Matrix
    {"node_label": "KEYWORD", "keyword_name": "simulation", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "reality", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "Neo", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "agents", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "machines", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "red pill", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "cyberpunk", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "philosophy", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "action", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "choice", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "mind-bending", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "The Oracle", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "Morpheus", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "virtual world", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "free will", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "cyber-reality", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "revolution", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "future dystopia", "movie_name": "The Matrix"},
    {"node_label": "KEYWORD", "keyword_name": "machine uprising", "movie_name": "The Matrix"},

    # Guardians of the Galaxy
    {"node_label": "KEYWORD", "keyword_name": "space", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "superheroes", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "action", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "comedy", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "teamwork", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "Peter Quill", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "Star-Lord", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "Rocket Raccoon", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "Gamora", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "Groot", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "adventure", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "galaxy", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "music", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "retro", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "villains", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "space opera", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "heartfelt moments", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "humor", "movie_name": "Guardians of the Galaxy"},
    {"node_label": "KEYWORD", "keyword_name": "eccentric team", "movie_name": "Guardians of the Galaxy"},

    # Avenger endgame
    {"node_label": "KEYWORD", "keyword_name": "Avengers", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Infinity Saga", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Superheroes", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Thanos", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Iron Man", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Captain America", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Time travel", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Endgame", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Battle of Wakanda", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Quantum Realm", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Hulk", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Thor", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Black Widow", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Hawkeye", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Thor's hammer", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Spider-Man", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Tony Stark", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Sacrifice", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Multiverse", "movie_name": "Avengers: Endgame"},
    {"node_label": "KEYWORD", "keyword_name": "Ant-Man", "movie_name": "Avengers: Endgame"},

    # The God father
    {"node_label": "KEYWORD", "keyword_name": "Mafia", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Family", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Crime", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Vito Corleone", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Don", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Corruption", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Power", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Al Pacino", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Marlon Brando", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Organized crime", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Blood feud", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Loyalty", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Justice", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Michael Corleone", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Sicily", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Crime syndicate", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Family business", "movie_name": "The Godfather"},
    {"node_label": "KEYWORD", "keyword_name": "Betrayal", "movie_name": "The Godfather"},

    # MOVIE: The Lion King
    {"node_label": "MOVIE", "movie_name": "The Lion King", "genre_name": "Animation"},
    {"node_label": "KEYWORD", "keyword_name": "Simba", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Pride Rock", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Circle of Life", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Mufasa", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Scar", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Africa", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Hakuna Matata", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Disney", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Animation", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Father-son bond", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Jungle", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Betrayal", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Nala", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "The Serengeti", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Friendship", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Royalty", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Overcoming fear", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Coming of age", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Circle of Life", "movie_name": "The Lion King"},

    # MOVIE: Gladiator
    {"node_label": "MOVIE", "movie_name": "Gladiator", "genre_name": "Action"},
    {"node_label": "KEYWORD", "keyword_name": "Gladiator", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Ancient Rome", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Maximus", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Russell Crowe", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Coliseum", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Commodus", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Battle", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Honor", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Rome", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Slave revolt", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Fight for freedom", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Marcus Aurelius", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Spinning wheel", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Betrayal", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Loyalty", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Epic battles", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Empire", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Courage", "movie_name": "Gladiator"},
    {"node_label": "KEYWORD", "keyword_name": "Historical drama", "movie_name": "Gladiator"},

    # The shining
    {"node_label": "KEYWORD", "keyword_name": "Jack Torrance", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Overlook Hotel", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Stephen King", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Psychological horror", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Kubrick", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Isolation", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Redrum", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Danny Torrance", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "The twins", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Haunting", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "The shining", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Crazy axe murderer", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Psychotic break", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Horror classic", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Kubrick's direction", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Snowstorm", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Madness", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Psychological thriller", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Wendy Torrance", "movie_name": "The Shining"},
    {"node_label": "KEYWORD", "keyword_name": "Hotel manager", "movie_name": "The Shining"},

    # Schindler's List
    {"node_label": "KEYWORD", "keyword_name": "Oskar Schindler", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Holocaust", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Jewish refugees", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Nazi regime", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Liam Neeson", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Steven Spielberg", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Krakow", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Survival", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Nazi officer", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "War drama", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Schindler's factory", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Red coat", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Germans", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Bravery", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Humanity", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Jewish survival", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "SS officers", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Emotional impact", "movie_name": "Schindler's List"},
    {"node_label": "KEYWORD", "keyword_name": "Inspiring story", "movie_name": "Schindler's List"},

    # The usual suspects
    {"node_label": "MOVIE", "movie_name": "The Usual Suspects", "genre_name": "Crime"},
    {"node_label": "KEYWORD", "keyword_name": "Keyser Söze", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "twist ending", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "Verbal Kint", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "crime thriller", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "Kevin Spacey", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "suspense", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "criminals", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "police interrogation", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "Kobayashi", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "conspiracy", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "mystery", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "unexpected ending", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "police detective", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "Heist", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "false identity", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "movie plot twist", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "corruption", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "film noir", "movie_name": "The Usual Suspects"},
    {"node_label": "KEYWORD", "keyword_name": "dark comedy", "movie_name": "The Usual Suspects"},

    # the social network
    {"node_label": "KEYWORD", "keyword_name": "Mark Zuckerberg", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "Facebook", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "social media", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "Harvard University", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "computer programming", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "entrepreneurship", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "startup culture", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "Sean Parker", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "business rivalry", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "legal battles", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "friendship", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "betrayal", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "drama", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "corporate politics", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "Napster", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "intellectual property", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "code", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "founder", "movie_name": "The Social Network"},
    {"node_label": "KEYWORD", "keyword_name": "social impact", "movie_name": "The Social Network"},

    # MOVIE: Pulp Fiction
    {"node_label": "MOVIE", "movie_name": "Pulp Fiction", "genre_name": "Crime"},
    {"node_label": "KEYWORD", "keyword_name": "John Travolta", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "Uma Thurman", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "Samuel L. Jackson", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "crime", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "drug deal", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "hitman", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "non-linear storytelling", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "pop culture", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "vengeance", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "suitcase", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "Los Angeles", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "gangsters", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "retro", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "dialogue", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "tragedy", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "comedy", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "double-cross", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "cult classic", "movie_name": "Pulp Fiction"},
    {"node_label": "KEYWORD", "keyword_name": "mob boss", "movie_name": "Pulp Fiction"},

    # MOVIE: The Godfather: Part II
    {"node_label": "MOVIE", "movie_name": "The Godfather: Part II", "genre_name": "Crime"},
    {"node_label": "KEYWORD", "keyword_name": "Marlon Brando", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "Al Pacino", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "mafia", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "Don Vito Corleone", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "family", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "crime syndicate", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "power", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "revenge", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "betrayal", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "Italian-American", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "Michael Corleone", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "organized crime", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "family legacy", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "The Corleone Family", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "Mafia wars", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "political corruption", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "cinematic masterpiece", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "fathers and sons", "movie_name": "The Godfather: Part II"},
    {"node_label": "KEYWORD", "keyword_name": "death", "movie_name": "The Godfather: Part II"},

    {"node_label": "KEYWORD", "keyword_name": "Tom Hanks", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "life journey", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "running", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "love story", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "Vietnam War", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "inspirational", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "autobiographical", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "innocence", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "disability", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "life lessons", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "shrimp business", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "Bubba", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "Jenny", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "Alabama", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "historical events", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "forgiveness", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "life and death", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "fate", "movie_name": "Forrest Gump"},
    {"node_label": "KEYWORD", "keyword_name": "the American dream", "movie_name": "Forrest Gump"},

    {"node_label": "KEYWORD", "keyword_name": "Brad Pitt", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "Tyler Durden", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "insomnia", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "anarchy", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "consumerism", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "identity crisis", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "violence", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "masculinity", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "underground fighting", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "soap", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "rebellion", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "mental health", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "narrator", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "corporate world", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "alter ego", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "self-destruction", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "rebirth", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "subversion", "movie_name": "Fight Club"},
    {"node_label": "KEYWORD", "keyword_name": "plot twist", "movie_name": "Fight Club"},

    {"node_label": "KEYWORD", "keyword_name": "Luke Skywalker", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Darth Vader", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Hoth", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Yoda", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Han Solo", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Princess Leia", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "The Force", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "dark side", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Boba Fett", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "cloud city", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "betrayal", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Luke vs Vader", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Lando Calrissian", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "The Rebel Alliance", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "sith", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "force ghost", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "Hoth battle", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "I am your father", "movie_name": "Star Wars: The Empire Strikes Back"},
    {"node_label": "KEYWORD", "keyword_name": "star destroyer", "movie_name": "Star Wars: The Empire Strikes Back"},

    {"node_label": "MOVIE", "movie_name": "The Wizard of Oz", "genre_name": "Fantasy"},
    {"node_label": "KEYWORD", "keyword_name": "Dorothy", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Yellow Brick Road", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Oz", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Scarecrow", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Tin Man", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Cowardly Lion", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Wicked Witch of the West", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Good Witch", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Munchkins", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Emerald City", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Dorothy's slippers", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Wizard", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Toto", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Fantasy world", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Over the rainbow", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Wicked Witch of the East", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Flying monkeys", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Good vs evil", "movie_name": "The Wizard of Oz"},
    {"node_label": "KEYWORD", "keyword_name": "Magic", "movie_name": "The Wizard of Oz"},

    {"node_label": "KEYWORD", "keyword_name": "Detention", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "High school", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Teenagers", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Clash of stereotypes", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Five students", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "John Bender", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Claire Standish", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Brian Johnson", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Allison Reynolds", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Andrew Clark", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Brat Pack", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Saturday detention", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Teen rebellion", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Self-discovery", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Coming of age", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Emotional growth", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Peer pressure", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Friendship", "movie_name": "The Breakfast Club"},
    {"node_label": "KEYWORD", "keyword_name": "Teen angst", "movie_name": "The Breakfast Club"},

    {"node_label": "KEYWORD", "keyword_name": "Time travel", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "DeLorean", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Marty McFly", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Doc Brown", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Hoverboard", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "1985", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "1955", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Time machine", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Flux capacitor", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Alternate timeline", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "80s nostalgia", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Family history", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Biff Tannen", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Peabody farm", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Rock and roll", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Marty's parents", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Back to the future series", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "Scientific invention", "movie_name": "Back to the Future"},
    {"node_label": "KEYWORD", "keyword_name": "DeLorean car", "movie_name": "Back to the Future"},

     {"node_label": "MOVIE", "movie_name": "The Revenant", "genre_name": "Adventure"},
    {"node_label": "KEYWORD", "keyword_name": "Survival", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Bear attack", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Nature", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Wild west", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Hugh Glass", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Harsh wilderness", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Survival instincts", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Fur trapping", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Lone survivor", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Pain", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Struggle for life", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Grizzly bear", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Leonardo DiCaprio", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Tom Hardy", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge quest", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Expedition", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "American frontier", "movie_name": "The Revenant"},
    {"node_label": "KEYWORD", "keyword_name": "Immense hardship", "movie_name": "The Revenant"},

    {"node_label": "KEYWORD", "keyword_name": "Illusion", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Magic", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Secrets", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Betrayal", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Duality", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "The secret trick", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Misdirection", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Rivalry", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Christopher Nolan", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Hugh Jackman", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Christian Bale", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Tesla", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Science vs. art", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Deception", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Murder", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Identity", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Sacrifice", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "Mastery", "movie_name": "The Prestige"},
    {"node_label": "KEYWORD", "keyword_name": "The Prestige", "movie_name": "The Prestige"},

    {"node_label": "KEYWORD", "keyword_name": "Thanos", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Infinity Stones", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Endgame", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Avengers", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Battle", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Superheroes", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Snap", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "War", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Wakanda", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Captain America", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Iron Man", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Thor", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Black Panther", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Doctor Strange", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Spider-Man", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Loki", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Gamora", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Vision", "movie_name": "Avengers: Infinity War"},
    {"node_label": "KEYWORD", "keyword_name": "Red Skull", "movie_name": "Avengers: Infinity War"},

    {"node_label": "KEYWORD", "keyword_name": "Teddy Daniels", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Insanity", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Psychiatric Hospital", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Twist Ending", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Delusion", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Investigation", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Murder", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Mental Illness", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Asylum", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Dreams", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Edward Daniels", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "U.S. Marshal", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Leo DiCaprio", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Chained", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Escape", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Conspiracy", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Memory", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Mystery Thriller", "movie_name": "Shutter Island"},
    {"node_label": "KEYWORD", "keyword_name": "Psychological", "movie_name": "Shutter Island"},

    {"node_label": "KEYWORD", "keyword_name": "Pandora", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Na'vi", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Jake Sully", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Environmentalism", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Colonization", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Indigenous People", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Avatar Program", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Military", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Sci-Fi Action", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "James Cameron", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "3D", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Visual Effects", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Human vs Nature", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Flying Creatures", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Tree of Souls", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Battle for Pandora", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Cultural Clash", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Exotic Animals", "movie_name": "Avatar"},
    {"node_label": "KEYWORD", "keyword_name": "Connection with Nature", "movie_name": "Avatar"},

    {"node_label": "KEYWORD", "keyword_name": "World War II", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Nazis", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Kill the Nazis", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Tarantino", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Brad Pitt", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Shosanna Dreyfus", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Basterds", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Django Unchained", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Historical Fiction", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Cinema", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Brad Pitt's Accent", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Bounty Hunters", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge Fantasy", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Nazi Officers", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Sgt. Donny Donowitz", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Operation Kino", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Tension", "movie_name": "Inglourious Basterds"},
    {"node_label": "KEYWORD", "keyword_name": "Germans", "movie_name": "Inglourious Basterds"},

    {"node_label": "MOVIE", "movie_name": "The Dark Knight Rises", "genre_name": "Action"},
    {"node_label": "KEYWORD", "keyword_name": "Bane", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Bruce Wayne", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Gotham City", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Batman", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Harvey Dent", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Terrorism", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "The League of Shadows", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Catwoman", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "End of Gotham", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Wayne Enterprises", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Prison Escape", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Brutality", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Underground Fight", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Chaos", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Bane's Revolution", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Courage", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Fear", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "Bomb", "movie_name": "The Dark Knight Rises"},
    {"node_label": "KEYWORD", "keyword_name": "The Bat", "movie_name": "The Dark Knight Rises"},


    {"node_label": "KEYWORD", "keyword_name": "Shark", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Amity Island", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Brody", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Quint", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Hooper", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Summer", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Beach", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Horror", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Suspense", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Survival", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Killer Shark", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Ocean", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Shark Attack", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Fishing Boat", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Screams", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Fear", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Chasing", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Boat Chase", "movie_name": "Jaws"},
    {"node_label": "KEYWORD", "keyword_name": "Island", "movie_name": "Jaws"},

    {"node_label": "KEYWORD", "keyword_name": "Rick Blaine", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Ilsa Lund", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Laszlo", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Vichy France", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Rick's Café", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Resistance", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "World War II", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Morocco", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Love triangle", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Paris", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Escape", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Nazis", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Humphrey Bogart", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Ingrid Bergman", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Music", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "As Time Goes By", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Casablanca airport", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Betrayal", "movie_name": "Casablanca"},
    {"node_label": "KEYWORD", "keyword_name": "Sacrifice", "movie_name": "Casablanca"},

    {"node_label": "KEYWORD", "keyword_name": "Luke Skywalker", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Princess Leia", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Han Solo", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Darth Vader", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "The Force", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Death Star", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Millennium Falcon", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Alderaan", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Tatooine", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Obi-Wan Kenobi", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Stormtroopers", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Lightsaber", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Jedi", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Rebel Alliance", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "Imperial Forces", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "X-Wing Fighter", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "C-3PO", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "R2-D2", "movie_name": "Star Wars: A New Hope"},
    {"node_label": "KEYWORD", "keyword_name": "The Dark Side", "movie_name": "Star Wars: A New Hope"},

    {"node_label": "KEYWORD", "keyword_name": "Neo", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Trinity", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Morpheus", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Agent Smith", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "The Oracle", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "The Architect", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Zion", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "The Matrix", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Red Pill", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Blue Pill", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Reality", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Simulation", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Sentinels", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Exile Programs", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Keymaker", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Merovingian", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Oracle's Prophecy", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Fight Scenes", "movie_name": "The Matrix Reloaded"},
    {"node_label": "KEYWORD", "keyword_name": "Bullet Time", "movie_name": "The Matrix Reloaded"},

    {"node_label": "KEYWORD", "keyword_name": "Westley", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Buttercup", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Inigo Montoya", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Vizzini", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Fezzik", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Dread Pirate Roberts", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Miracle Max", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "The Cliffs of Insanity", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "True Love", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "As You Wish", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "The Princess", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Sword Fight", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Marriage", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "R.O.U.S.", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Battle of Wits", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Booing", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "Rodents of Unusual Size", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "You Killed My Father", "movie_name": "The Princess Bride"},
    {"node_label": "KEYWORD", "keyword_name": "The Fire Swamp", "movie_name": "The Princess Bride"},

    {"node_label": "KEYWORD", "keyword_name": "Dinosaurs", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "T-Rex", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Velociraptor", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Isla Nublar", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Jurassic Park", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "John Hammond", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Dr. Alan Grant", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Dr. Ellie Sattler", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Ian Malcolm", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Amber", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "DNA", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Jurassic World", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "The Lost World", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Raptors", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Theme Park", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Fossils", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Electric Fence", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Brachiosaurus", "movie_name": "Jurassic Park"},
    {"node_label": "KEYWORD", "keyword_name": "Park Visitors", "movie_name": "Jurassic Park"},

    {"node_label": "KEYWORD", "keyword_name": "Truman Burbank", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Reality TV", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Fake Reality", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Christof", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "The Truman Show", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Surveillance", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Media Manipulation", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Hidden Camera", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Simulation", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Island", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Inception", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Isolation", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Truth", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Freedom", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Escape", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Reality", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Control", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Audience", "movie_name": "The Truman Show"},
    {"node_label": "KEYWORD", "keyword_name": "Cynthia", "movie_name": "The Truman Show"},

    {"node_label": "KEYWORD", "keyword_name": "Superheroes", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Incredible Family", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Bob Parr", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Helen Parr", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Mr. Incredible", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Elastigirl", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Dash Parr", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Violet Parr", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Frozone", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Syndrome", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Superpowers", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Villain", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Secret Identity", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Superhero Family", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Action", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Underminer", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Incredible Suit", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Incredible Power", "movie_name": "The Incredibles"},
    {"node_label": "KEYWORD", "keyword_name": "Superhero Ethics", "movie_name": "The Incredibles"},

    {"node_label": "KEYWORD", "keyword_name": "Simba", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Pumbaa", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Timon", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Mufasa", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Scar", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Pride Rock", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Hakuna Matata", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Circle of Life", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Nala", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Rafiki", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Kingdom", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Lion Pride", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Legacy", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Family", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Adventure", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Nature", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Friendship", "movie_name": "The Lion King"},
    {"node_label": "KEYWORD", "keyword_name": "Growth", "movie_name": "The Lion King"},

    {"node_label": "KEYWORD", "keyword_name": "T-800", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Skynet", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "John Connor", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Sarah Connor", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Cyberdyne Systems", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Judgment Day", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Terminator", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Time Travel", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Future War", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Arnold Schwarzenegger", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Robert Patrick", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Cybernetic Organism", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Action", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Robots", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Artificial Intelligence", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Chase", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Machine vs Human", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Survival", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Revenge", "movie_name": "Terminator 2: Judgment Day"},
    {"node_label": "KEYWORD", "keyword_name": "Sacrifice", "movie_name": "Terminator 2: Judgment Day"},
]



# function to connect to driver
def connect_to_driver(uri, user_name, password):
    driver = GraphDatabase.driver(uri, auth=(user_name, password))
    return driver

# function to create a db
def create_user_database(driver, user_name, db_name):  
    with driver.session() as session:
        session.run(f"CREATE DATABASE {db_name};")
        session.run(f"ALTER USER {user_name} SET HOME DATABASE {db_name};")
        print(f"Database '{db_name}' created and set as home for user '{user_name}'.")

# helper function for executing queries
def run_query_list_on_tx(tx, queries):
    start_time = time.time()
    results = []
    for query in queries:
        print("Executing query: {0}".format(query))
        result = tx.run(query)
        results.append(result)
    end_time = time.time()
    print(f"Executing queries took {end_time - start_time} seconds")
    return results

'''
first approach with apoc single query
'''
def run_query_list_on_tx_with_apoc(tx, queries):
    start_time = time.time()

    # a single apoc query to run all the queries
    apoc_query = "UNWIND $queries AS query CALL apoc.cypher.run(query, {}) YIELD value RETURN count(value)"
    
    # running apoc o process all the queries
    result = tx.run(apoc_query, queries=queries)

    end_time = time.time()
    print(f"Executing queries with APOC took {end_time - start_time} seconds")
    return result

'''
second approach using a peroidic iteraite
'''
def run_query_list_on_tx_with_periodic(tx, queries):
    start_time = time.time()
    
    periodic_query = """
    CALL apoc.periodic.iterate(
      "UNWIND $queries AS query RETURN query",
      "CALL apoc.cypher.run(query, {}) YIELD value RETURN value",
      {batchSize: 100}
    ) YIELD batches, total
    RETURN batches, total
    """
    result = tx.run(periodic_query, queries=queries)
    
    end_time = time.time()
    print(f"Executing queries with `apoc.periodic.iterate` took {end_time - start_time} seconds")
    return result


'''
function to create nodes for now the nodes is going to be 300 nodes
'''
def create_nodes(driver, nodes):
    query_list = []

    for node in nodes:
        if node["node_label"] == "GENRE":
            query = f"""
            MERGE (n:{node['node_label']}{{name:"{node['genre_name']}"}})
            RETURN n;
            """
        elif node["node_label"] == "MOVIE":
            # Merge Movie Node and link to Genre
            query = f"""
            MERGE (m:{node['node_label']}{{name:"{node['movie_name']}"}})
            MERGE (g:GENRE{{name:"{node['genre_name']}"}})
            MERGE (m)-[:BELONGS_TO]->(g)
            RETURN m, g;
            """
        elif node["node_label"] == "KEYWORD":
            # Merge Keyword Node and link to Movie
            query = f"""
            MATCH (m:MOVIE {{name:"{node['movie_name']}"}})
            MERGE (k:KEYWORD {{name:"{node['keyword_name']}"}})
            MERGE (k)-[:ASSOCIATED_WITH]->(m)
            RETURN k, m;
            """    
        query_list.append(query)

    # executing queries
    with driver.session(database=db_name) as session:
        session.execute_write(run_query_list_on_tx_with_apoc, query_list)
    print("DONE SIR")    
        
def run_query(driver, db_name):
    with driver.session(database=db_name) as session:
        result = session.run("MATCH (n) RETURN n LIMIT 5")
        for record in result:
            print(record)

if __name__ == "__main__":
    driver = connect_to_driver(uri, user_name, password)
    # create_user_database(driver, user_name, db_name)
    # run_query(driver, db_name)
    create_nodes(driver, nodes)
    # with driver.session(database="cypheropti") as session:
    #     session.run("CREATE (n:GENRE {name: 'TestGenre'}) RETURN n")
